//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginInDevim.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_In_Proj
    {
        public int id { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<int> id_proj { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual Users Users { get; set; }
    }
}
